name: da_yan_app
description: "大雁APP，基于Flutter实现的一款BLE低功耗蓝牙定位查找应用程序。"

publish_to: 'none'

version: 0.0.2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  amap_flutter_map:
    path: /Users/wyg/Flutter/flutter_plugins/amap_flutter_map
  amap_flutter_base:
    path: /Users/wyg/Flutter/flutter_plugins/amap_flutter_base
  amap_flutter_location:
     path: /Users/wyg/Flutter/flutter_plugins/amap_flutter_location
  permission_handler: ^11.0.1
  flutter_blue_plus: ^1.30.3
  dio: ^5.4.0
  flutter_native_splash: ^2.3.8
  snapping_bottom_sheet: ^1.0.4
  provider: ^6.0.4
  shared_preferences: ^2.2.2
  map_launcher: ^3.1.0
  font_awesome_flutter: ^10.1.0
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  page_transition: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
# material3
  uses-material-design: true
  
  assets:
    - assets/
    - assets/markers/

# 启动图标
flutter_icons:
  image_path: "assets/launch/logo.png"
  android: true
  ios: true

# 启动动画
flutter_native_splash:
  color: "#ffffff"
  image: assets/launch/splash.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    image: assets/launch/android12splash.png

    # Splash screen background color.
    # color: "#ffffff"

    # App icon background color.
    # icon_background_color: "#ffffff"

    # The branding property allows you to specify an image used as branding in the splash screen.
    branding: assets/launch/android12splash_branding.png

  web: false

  fullscreen: true
